In this exercise, we are going to perform a few simple matrix operations.

In [1]:
import numpy as np

In [2]:
a = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
b = np.matrix('1 0 0; 0 2 0; 0 0 3')

c = a * b
print(c)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [9]:
bInv = b.getI()
print(bInv)

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]


In [10]:
cTrans = c.getT()
print(cTrans)

[[ 1  4  7]
 [ 4 10 16]
 [ 9 18 27]]
